services:
  - type: web
    name: realtime-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: api/Dockerfile
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: realtime-web
    env: docker
    plan: free
    branch: main
    dockerfilePath: web/Dockerfile
    autoDeploy: true